# Configuration du serveur
spring.application.name=MediPay
server.port=${PORT:8008}

# Profile actif par default
spring.profiles.active=prod

#Peut causer des problemes de performance s'il est a true
spring.jpa.open-in-view=false

spring.jackson.serialization.indent_output=true
logging.level.org.springframework.security=DEBUG

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
# 1 jour en millisecondes
#application.security.jwt.expiration=86400000
#15Min
#application.security.jwt.expiration=900000
#1min
application.security.jwt.expiration=60000

#End point
app.env.apiUrl=${API_URL}
app.base.url=${BASE_URL}

# Configuration des emails
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Configuration Brevo SMTP
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_APP_NAME}
brevo.recipient.email=${BREVO_RECIPIENT_EMAIL}