# Configuration du serveur
spring.application.name=MediPay
server.port=${PORT:8008}

# Profile actif par default
spring.profiles.active=dev

#Peut causer des problemes de performance s'il est a true
spring.jpa.open-in-view=false

spring.jackson.serialization.indent_output=true
logging.level.org.springframework.security=DEBUG

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
# 1 jour en millisecondes
#application.security.jwt.expiration=86400000
#15Min
application.security.jwt.expiration=900000